name: Scrape ArXiv

on:
  schedule:
   - cron:  '0 0 * * 0'
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'true'
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: scrape the arxiv
      run: |
        pip install -r requirements.txt
        cd up_scraper
        python main.py
        
    - run: git pull
          
    - name: Committing changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add new data
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
